apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: d293aW1zb3NlY3VyZQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: db-person-secret
type: Opaque
data:
  DB_PERSON_PASSWORD: d293aW1zb3NlY3VyZQ==