apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: d293aW1zb3NlY3VyZQ==
  ---
  apiVersion: v1
kind: Secret
metadata:
  name: db-persons-secret
type: Opaque
data:
  DB_PASSWORD: d293aW1zb3NlY3VyZQ==