apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-ingestion-service
  name: location-ingestion-service
spec:
  ports:
  - name: "5555"
    port: 5555
    targetPort: 5555
    nodePort: 30020
  selector:
    service: location-ingestion-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-ingestion-service
  name: location-ingestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-ingestion-service
  template:
    metadata:
      labels:
        service: location-ingestion-service
    spec:
      containers:
      - image: fklein21/nd064-udaconnect-location-ingestion-service:latest
        name: location-ingestion-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
